### ISSUE TITLE
Template_Node_Response Model needs more Fields

### ISSUE THREAD

**Issue by JerCarnahan** [Likhovodov/Simulated-Conversations#7]
There is currently no place to link audio files (for responses), and no field for a researcher to give feedback per node.
A field for overall feedback could also be useful in Template_Response.

**Comment by kaigoos** [comment]
In my opinion I think it's okay to go ahead and add a FileField to the model that you need it for. It's something that is necessary anyways so no need to wait for others approval if it is going to hold you up from making progress. 

For the feedback per node I can't comment on it since I don't remember how we planned on implementing it.

**Comment by devin-w-hill** [comment]
I agree, if it's holding you up then go ahead and add what you need and we can discuss in the review. FileField and two CharFields seems like all you'd need
